global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics/prom
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: antifraud
    metrics_path: /metrics/prom
    static_configs:
      - targets: ["host.docker.internal:3001"]

  - job_name: antifraud_worker
    metrics_path: /metrics/prom
    static_configs:
      - targets: ["host.docker.internal:3101"]
