global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics/prom
    static_configs:
      - targets: ["go-gateway:8080"]

  - job_name: antifraud
    metrics_path: /metrics/prom
    static_configs:
      - targets: ["nestjs:3000"]

  - job_name: antifraud_worker
    metrics_path: /metrics/prom
    static_configs:
      - targets: ["nestjs-worker:3101"]
