services:

  nextjs:
    build: .
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"
    user: "0:0"
    environment:
      API_BASE_URL: http://app:8080
    ports:
      - 3002:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "app:host-gateway"
    networks:
      - go-gateway_default

      
networks:
  go-gateway_default:
    external: true
